name: Linting Check

on:
  push:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Lint frontend code
        working-directory: frontend
        run: npm run lint

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Lint backend code
        working-directory: backend
        run: npm run lint
